### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by reglayass** [StudieverenigingSTORM/knt#15]
- [x] Admins
    - Are able to see all information about users + products
    - Are able to edit user and product information
- [x] Users
    - Are only able to see products and their own balance

**Comment by tudurom** [comment]
Pretty much. But for ease of implementation and security, I think that admins should be different entities than users (i.e. admins cannot get drinks and snacks). This way, we don't need to modify user permissions on every board change, we can't forget to revoke permissions.

For the authentication method, I think it's enough to use HTTP Basic authentication, using strings like `user:<id>` and `admin:<id>` for username and the password for, well, password.

**Comment by TadMaj** [comment]
For authentication the last thing that is needed to be implemented is an admin action tracker. A long side that this is a bit off topic, but we need more general logging for the knt

- [x]  Admin logging
- [x]  General logging
