### ISSUE TITLE
The frontend debate: what pieces of web tech?

### ISSUE THREAD

**Issue by tudurom** [StudieverenigingSTORM/knt#2]
I'd argue against any kind of Single Page Application thing (so no routing libraries and whatnot).

To guarantee underlying simplicity for this application and low resource usage for the client, I propose doing the client "like in the good old days": make the backend server (also) serve the HTML/CSS/JS. If done correctly, you can get a very snappy application, without having to deal with routers, state management and so on. You can even make it go faster with things like [Turbo](https://turbo.hotwired.dev/) (similar to Turbolinks if you dipped your toes in Ruby on Rails before).

**Comment by reglayass** [comment]
Some Single-Parge-Application frameworks do include libraries for routing: React and Vue are two that I am most familiar with. I believe you can combine vue/react and flask together as well. (or did i misunderstand what you meant "so no routing libraries and whatnot"

**Comment by tudurom** [comment]
For now let's agree for nuxt
