### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by reglayass** [StudieverenigingSTORM/knt#5]
For the time being, there is a minimal sqlite db on the repo in order to deal with users and products. Next step is to figure out where the real database is going to be.

**Comment by tudurom** [comment]
The real database should still be an sqlite one, we should just have a config key for specifying where it should be stored.

**Comment by tudurom** [comment]
Uh I think we all agree on this, closing.

**Comment by vmcj** [comment]
> Uh I think we all agree on this, closing.

Personally I would prefer a MariaDB, as it makes integration for future tools easier. Having multiple projects write to the same sqlite DB is IMO not the smartest idea.
