### ISSUE TITLE
KnT frontend design

### ISSUE THREAD

**Issue by reglayass** [StudieverenigingSTORM/knt#7]
So that the front-end developer in these parts (me) can actually have something to work off of. I am unfortunately not a designer. This design could also serve for other people (not me) as a good exercise in javascript.

**Comment by tudurom** [comment]
We could take as a starting point the current one concerning the layout. It's very easy to code with css i think now that css grid exists.

**Comment by reglayass** [comment]
I am using the bootstrap-vue package in Nuxt and this would be eez peez to do. We can also just do plain CSS from scratch, but bootstrap-vue is a well-maintained package and easy to use, so I would prefer to use it to make everyone's lives easier.

**Comment by vmcj** [comment]
> I am using the bootstrap-vue package in Nuxt and this would be eez peez to do. We can also just do plain CSS from scratch, but bootstrap-vue is a well-maintained package and easy to use, so I would prefer to use it to make everyone's lives easier.

The only argument against this I can come up with; I think when you just finished Webtech as a course you should be able to help with this project... is it easy enough to propose changes if you didn't invest time in learning vue?

**Comment by reglayass** [comment]
I would argue its a good skill anyway to know a JS framework or two, if you have some basic vanilla js knowledge. And I am available to teach/answer questions, Vue is my day job.

**Comment by tudurom** [comment]
I am going to work on a mockup.
