### ISSUE TITLE
Update wiki with flask + nuxt setup information + extra

### ISSUE THREAD

**Issue by reglayass** [StudieverenigingSTORM/knt#9]
What is needed:

- [ ] Flask setup information
- [ ] Nuxt setup information
- [ ] Extra information
    - simple instructions about database, flask-restful, models and schemas, etc
- [ ] Relevant documentation

**Comment by tudurom** [comment]
I think setup information should be easy to access in the readme and "architectural" information and documentation should be in the wiki.
